# Generated by Django 5.2.4 on 2025-08-05 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("borrowings", "0003_payment"),
    ]

    operations = [
        migrations.RenameField(
            model_name="payment",
            old_name="status",
            new_name="payment_status",
        ),
        migrations.RenameField(
            model_name="payment",
            old_name="amount",
            new_name="user_amount",
        ),
    ]
