# Generated by Django 5.2.4 on 2025-08-05 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("borrowings", "0005_alter_payment_payment_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="payment_type",
            field=models.CharField(
                choices=[("BORROWING", "Borrowing"), ("FINE", "Fine")],
                default="BORROWING",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Paid", "Paid"),
                    ("Failed", "Failed"),
                ],
                default="Pending",
                max_length=10,
            ),
        ),
    ]
